### ISSUE TITLE
Install Kats with CMDSTANPY instead of pystan

### ISSUE THREAD

**Issue by lcoulet** [facebookresearch/Kats#103]
Hello, as for prophet it would more than nice to have the ability to avoid installing the pystan software.

e.g. for fbprophet we can proceed as follows:
`CMDSTAN=/tmp/cmdstan-2.22.1 STAN_BACKEND=CMDSTANPY pip install prophet`

Would that be possible to install Kats the same way ? And to document in the readme ?

**Comment by michaelbrundage** [comment]
I'm not familiar with CMDSTANPY, but if you want to experiment with this yourself, you could clone Kats, remove the `pystan` line from requirements.txt, and run `pip install .` in the root directory of Kats to install it. If `CMDSTANPY` is importable as `import stan` that should just drop-in work; otherwise, you would also need to modify the places in Kats where it has `import stan`. To fix #101 , I will make `pystan` an optional import.

**Comment by michaelbrundage** [comment]
After I landed  f6d9d94 to fix issue #101, you should now be able to do this by first installing minimal Kats:

```
MINIMAL=1 pip install .
```

which will omit pystan and prophet, and then you're free to install optional other dependencies as desired.
