### ISSUE TITLE
PIP istall kats doesnot work for windows 10

### ISSUE THREAD

**Issue by asterixas** [facebookresearch/Kats#137]
Hi, i have issue in connection with installing kats library. In windows 10 I get errors.

**Comment by asterixas** [comment]
Yes I tried unistalling numpy and then pip install kats, but I get  ERROR: Could not find a version that satisfies the requirement numpy==1.20.0. It is first when I cannot install package to python.

**Comment by conclaudio** [comment]
> Yes I tried unistalling numpy and then pip install kats, but I get ERROR: Could not find a version that satisfies the requirement numpy==1.20.0. It is first when I cannot install package to python.

Try to reinstall numpy (I actually have ver. 1.20.1, python 3.8.5 ). I hope this works.

ps. I had also similar issues with statsmodels (should be 0.13.0) and pystan (should be 2.19.1.1).

**Comment by sniperlucian** [comment]
did you get it intalled?

**Comment by SakshiNYCU** [comment]
> Hello, I have the same problem in installing kats on a new environnent conda (conda create --name "envs" python=3.8). The error seems to come from numpy and/or fbprohet. I tried to install fbprophnet independently with (conda install -c conda-forge fbprophet) with success but i am not able after to install kats. Thank you

Were you able to install Kats later? If yes, please share how. Thank you

**Comment by fernandochafim** [comment]
I was able to install kats following these steps:

(1) pip install pystan==2.19.1.1
(2) conda install gcc 
(3) conda install -c conda-forge fbprophet
(4) pip install kats

**Comment by saonideb** [comment]
Hi @vincentvic ,
I am facing the same issue.
Were you able to install after that? If, yes do share. 
Thank you!

**Comment by juanyanli-db** [comment]
@michaelbrundage do we have any timeline on relaxing the requirement on `statsmodels` (e.g. upgrade to `0.13.2`)?

**Comment by asterixas** [comment]
Fernando thank you!!!
I cannot believe but it works. I had problem with command:conda install gcc
But anyway the result is that I have kats package installed
Thank you

**Comment by NatalieCarder** [comment]
Hi there, I am encountering the same error when trying to install kats on python=3.9. 
The error seems to be due to a blocker installing fbprophet ("ERROR: Failed building wheel for fbprophet")
When trying to install fbprophet independently using the steps above, I get an error at step 3 (conda install -c conda-forge fbprophet). The error suggests fbprophet is not compatible with python version 3.9: 
"fbprophet -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']
Your python: python=3.9"
I just wanted to check if anyone has a solution to use Kats on Python 3.9 or if I should downgrade to a minor version? Alternatively, are there any solutions to installing Kats but without fbprophet? Would appreciate any guidance as I was really looking forward to using Kats!
Thanks

**Comment by michaelbrundage** [comment]
The `fbprophet` issue is tracked elsewhere (e.g., #249 ). The `statsmodels` issue is complex and requires fixing the many places `statsmodels` has broken Kats (PRs welcome!). We can't support dependency installation issues such as `numpy` failing to install.

This issue is old and has grown to include many additional unrelated issues. Closing for now; please open distinct issues for each specific issue.

**Comment by Asha-Choudhary** [comment]
It doesn't work on windows, period!

**Comment by waqarahmed6095** [comment]
I tried this and it is working
conda create -n katsenv python=3.7
conda activate katsenv
conda install -c conda-forge fbprophet
conda install prophet
pip install install kats
downgrade pandas to 1.3.0 
downgrade packaging to 21.3
change super().__init__(*args, **kwargs) to super().__init__() on line 178 of registry.py in site-packages\holidays\registry.py of anaconda environment
