### ISSUE TITLE
tsfeatures.TsFeatures.transform() produces nan values

### ISSUE THREAD

**Issue by chrischia06** [facebookresearch/Kats#79]
the TsFeatures.transform() seems to produce some nan values when using all feature groups , for the Holt-Winters features and the changepoint detection features

An example of the error can be found at [https://colab.research.google.com/drive/13t3Gy9vazkeb8J32Zv-dijuww03GDbE7?usp=sharing](https://colab.research.google.com/drive/13t3Gy9vazkeb8J32Zv-dijuww03GDbE7?usp=sharing), using the air passengers dataset from https://github.com/facebookresearch/Kats/blob/master/kats/data/air_passengers.csv, and stock price data from the yfinance library

**Comment by thomashydeli** [comment]
Hi, chrischia06! Thanks for bringing up the question. I've noticed that you didn't wrap your time series in TimeSeriesData object from Kats.consts, which was causing failures when we call detectors to perform detections to get CUSUM, Bayesian Changepoint, Trend features. After wrapping the time series up into a TimeSeriesData object, you should see these features are not null any more. Here's a quick example: https://colab.research.google.com/drive/1XqBbcNcKW_5Boe35bACYff7Id9PHc3aV?usp=sharing

As for holt-winters features, this is due to that we apply box-cox transformation on data when getting these features via exponential smoothing in statsmodels, and this requires the data to be strictly non-negative, which is not true in the percentage changes in stock data.

Lemme know if there's any question, and I'll close this issue for now. Thanks!
