### ISSUE TITLE
Issue when trying to instantiate BackTesterSimple object using TimeSeriesData object with repeating minute bars on separate days

### ISSUE THREAD

**Issue by mturk24** [facebookresearch/Kats#91]
Hi there,

When running some of the code from the backtesting section of the tutorials as seen below,

`params = ARIMAParams(p=2, d=1, q=1)
ALL_ERRORS = ['mape', 'smape', 'mae', 'mase', 'mse', 'rmse']

backtester_arima = BackTesterSimple(
    error_methods=ALL_ERRORS,
    data=air_passengers_ts,
    params=params,
    train_percentage=75,
    test_percentage=25, 
    model_class=ARIMAModel)

backtester_arima.run_backtest()`

there is an issue if you try to replace the air_passengers_ts data with a TimeSeriesData object which contains minute bars that repeat on separate days. For instance, the 'time' column of some new TimeSeriesData object X is of the format 2012-01-02 09:30:00 for row 1 (or rather, x_1) and of the format 2012-01-02 09:31:00 for row 2 (or rather, x_2). 

When trying to instantiate a BackTesterSimple object using this data, it succeeds if there is only 1 day's worth of minute bar data. However, if we also have a second day's worth of data with the format  2012-01-03 09:30:00 (x_392) and 2012-01-03 09:31:00 (x_393) and so on... up until the end of the end of the same sequence of minute bars as the previous day, then the code fails with error:

> ValueError: No frequency information was provided with date index and no frequency could be inferred.

**Comment by Axemen** [comment]
Hey @mturk24, 

The problem you're encountering is most likely caused by a time gap within your data.

This is because KATS cannot infer the underlying frequency of the data when there are gaps within it. 

You can reproduce this issue with the example below 

The working example 
```
dates = pd.date_range("2020-01-01 00:00:00", end='2020-01-02 12:00:00', freq='T')

data = pd.DataFrame({
    "time": dates,
    "value": [np.random.random() for _ in range(len(dates))]
})

ts = TimeSeriesData(data)

params = ARIMAParams(p=2, d=1, q=1)
ALL_ERRORS = ['mape', 'smape', 'mae', 'mase', 'mse', 'rmse']

backtester_arima = BackTesterSimple(
    error_methods=ALL_ERRORS,
    data=ts,
    params=params,
    train_percentage=75,
    test_percentage=25, 
    freq='T',
    model_class=ARIMAModel)

backtester_arima.run_backtest()
```

An example with a gap in the data causing the ValueError:  No frequency information was provided with date index and no frequency could be inferred.
```
dates = list(pd.date_range(start="2020-01-01 00:00:00", end="2020-01-01 12:00:00", freq='T')) + \
    list(pd.date_range(start="2020-01-02 00:00:00", end="2020-01-02 12:00:00", freq='T'))

data = pd.DataFrame({
    "time": dates,
    "value": [np.random.random() for _ in range(len(dates))]
})

ts = TimeSeriesData(data)

params = ARIMAParams(p=2, d=1, q=1)
ALL_ERRORS = ['mape', 'smape', 'mae', 'mase', 'mse', 'rmse']

backtester_arima = BackTesterSimple(
    error_methods=ALL_ERRORS,
    data=ts,
    params=params,
    train_percentage=75,
    test_percentage=25, 
    freq='T',
    model_class=ARIMAModel)

backtester_arima.run_backtest()
```

**Comment by rohanfb** [comment]
Hi @mturk24,

Based on the description of your use case, it sounds like you're trying to backtest price predictions on some sort of financial time series. In that case, there's a couple of different things to unpack here.

Depending on the exact instrument you're looking at, the calendar, especially at the minutely level, can be fairly irregular. For example, a standard equity that is traded on a US exchange like NASDAQ trades generally 252 days out of the year, and a few of these days have shortened trading hours as well. Any type of date time aware prediction is going to be especially tricky here, and due to the well-defined frequency requirements of models like ARIMA, you'll run into errors on the `statsmodels` side. Here are some alternatives:
           - Resample the data into wider, equal intervals.
           - Use a different model. `ProphetModel` should support your use case, and I've tested and confirmed it works correctly on an equity minute bars dataset. Additionally, `ProphetParams` also has additional arguments that may be able to better support some of the nuances of your use case.
           - `ArimaModel` can work if you remove the `datetime` component of the series, but this is not supported in Kats currently (see #67). We may support this in the future, but for now you can replace the `time` column of your `TimeSeriesData` with dummy values, depending on your exact use case.  

Also keep in mind that `ArimaModel` can have some limitations when forecasting on financial time series data. I would pay special attention to items such as the stationarity assumptions of ARIMA, as well as the assumptions regarding interval length when dealing with lagged variables. 

Hope this helps!
