### ISSUE TITLE
Very inflexible plotting - allow instead for an axis as argument

### ISSUE THREAD

**Issue by nemonominem** [facebookresearch/Kats#92]
The way some of the plotting is done right now is very limiting.
For instance kats/detectors/cusum_detection.py ends with a  plt.show().

It would be better to allow the caller to manage the figure itself and pass an axis (as in most typical graphing utilities). This way one could build composite figures or decide where to plot (to an html file for instance).

**Comment by michaelbrundage** [comment]
Totally agree, and I've been submitting diffs to address this. Methods are being changed to accept `plt.Axes` and other user-configurable properties as appropriate, return `plt.Axes`, and not invoke `plt.show`.

**Comment by michaelbrundage** [comment]
Hi @nemonominem, I'm going to resolve this issue. There's never-ending work to further improve our APIs, but over a series of more than a dozen diffs I've removed all the `plt.show()` and `sns.set()` invocations (except for one lingering one in `detectors/bocpd.py`) and updated most `plot()` methods to accept `plt.Axes` (except when the method generates multiple plots), give users more control over some previously hard-coded values, and return `plt.Axes` or a sequence of `plt.Axes` so that users can further modify the plots before rendering. If you run into more limitations with the plotting methods, please open new issues for the specific problems. Thanks!
