### ISSUE TITLE
Kats Tutorial 101_basics - Prophet predict method

### ISSUE THREAD

**Issue by young-hun-jo** [facebookresearch/Kats#94]
Hi, first, Thanks for your awesome time-series analysis framework for everyone! 
I am following your tutorial of Kats(101_basics) but I wondered what meaning of argument ``freq="MS"`` in ``predict`` method. What is the meaning of ``freq`` and how can I set the other ``freq`` parameter in addtition to ``"MS"``? 

Below, here is the screenshot of your tutorial, Thanks!
<img width="550" alt="스크린샷 2021-07-24 오후 7 20 20" src="https://user-images.githubusercontent.com/54783194/126865514-821a6d00-67d9-4875-8c23-c3e4955b2662.png">

**Comment by Axemen** [comment]
Hey @young-hun-jo, 

The `freq` kwarg for the predict method in the predict functionality of models allows you to specify the frequency that the model is making predictions. 

Let's say that I wanted to predict in days `'D'` instead of month start `'MS'` I could just set my frequency to D instead. 

If the freq argument is not provided it will attempt to infer it from the data. 

The available frequencies are ones available in pandas which you can find [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases)

**Comment by young-hun-jo** [comment]
I got to know the kwarg ``freq`` thanks to you. I will close this issue.
